name: Commit Stage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run Ollama
        run: |
          docker run -d --name ollama -p 11434:11434 ghcr.io/thomasvitale/ollama-orca-mini

      - name: Logs Ollama
        run: |
          docker logs ollama

      - name: Test Ollama
        run: |
          docker exec -it ollama ollama list
      
      - name: LLM
        run: |
          curl -X POST http://localhost:11434/api/generate -d '{
            "model": "orca-mini",
            "prompt":"Why is the sky blue?"
          }'
