name: Commit Stage

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run Ollama
        run: |
          docker run -d --name ollama -p 11434:11434 ghcr.io/thomasvitale/ollama-orca-mini:d6298dc90cea748e37e97d9d75a051bd53403d47

      - name: Logs Ollama
        run: |
          sleep 10
          docker logs ollama

      - name: Test Ollama
        run: |
          curl http://localhost:11434
      
      - name: LLM
        run: |
          curl -X POST http://localhost:11434/api/generate -d '{
            "model": "orca-mini",
            "prompt":"Why is the sky blue?"
          }'
